openapi: 3.0.0
info:
  title: Hello API
  version: 1.0.0
paths:
  /api/hello:
    post:
      summary: Greet a user
      operationId: hello
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
